/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxtypes.h
 *  model: PositionControllerTilt
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:05:31 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the typedefs that are used for integers and
   doubles. All the generated code uses these typedefs to enhance
   flexibility (in case the compiler is not Visual C++ 6 or the destination
   platform is not Windows 2000 on a Pentium 4).
   
   The user should be aware of the precision of these types, when
   these types are changed! For instance, when the destination platform 
   is a particular 8051 that does not support any doubles at all,
   one might change the tilt_XXDouble type into some float of 4 bytes.
   The results may then differ from the 20-sim results. It is advised
   to check these differences by running the code with both settings
   on the PC first (as far as this is possible).
   
   In 20-sim the following definitions are used:
   
    typedef tilt_XXDouble double;
    typedef tilt_XXInteger int;
   
   so that 
   
    tilt_XXDouble is 8 bytes (64 bits) with a range of [-1.7E+308, 1.7E+308]
    tilt_XXInteger is 4 bytes (32 bits) with a range of [-2147483648, 2147483647]
    tilt_XXCharacter is 1 byte (8 bits) with a value of [0, 255]
    tilt_XXBoolean is 1 byte (8 bits) with a value of 0 or 1
*/ 

#ifndef TILT_TYPES_H
#define TILT_TYPES_H

/* The mentioned typedefs */
typedef double tilt_XXDouble;
typedef int tilt_XXInteger;
typedef char tilt_XXCharacter;
typedef char tilt_XXBoolean;
typedef const char* tilt_XXString;

/* Defines */
#define tilt_XXTRUE  1
#define tilt_XXFALSE 0

#endif

