/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:05:31 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "tilt_model.h"
#include "tilt_integ.h"
#include "tilt_funcs.h"
#include "tilt_submod.h"
#include "motionprofiles.h"
#include "EulerAngles.h"

/* The submodel I/O variables */
tilt_XXInteger tilt_xx_number_of_inputs = 3;
tilt_XXInteger tilt_xx_number_of_outputs = 1;

/* the names of the submodel io variables
   uncomment this part if you need these names
tilt_XXString tilt_xx_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
tilt_XXString tilt_xx_output_names[] = {
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void tilt_XXCopyInputsToVariables (tilt_XXDouble *u)
{
	/* Copy the input vector to the input variables */
	tilt_xx_V[8] = u[0];		/* corr */
	tilt_xx_V[9] = u[1];		/* in */
	tilt_xx_V[10] = u[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void tilt_XXCopyVariablesToOutputs (tilt_XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	tilt_xx_V[11];		/* out */

}

/* The initialization function for submodel */
void tilt_XXInitializeSubmodel (tilt_XXDouble *u, tilt_XXDouble *y, tilt_XXDouble t)
{
	/* Initialization phase (allocating memory) */
	tilt_xx_initialize = tilt_XXTRUE;
	tilt_xx_steps = 0;
	tilt_XXModelInitialize ();
	tilt_XXDiscreteInitialize ();

	/* Copy the inputs */
	tilt_xx_time = t;
	tilt_XXCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	tilt_XXCalculateInitial ();
	tilt_XXCalculateStatic ();
	tilt_XXCalculateInput ();
	tilt_XXCalculateDynamic ();
	tilt_XXCalculateOutput ();

	/* Set the outputs */
	tilt_XXCopyVariablesToOutputs (y);

	/* End of initialization phase */
	tilt_xx_initialize = tilt_XXFALSE;
}

/* The function that calculates the submodel */
void tilt_XXCalculateSubmodel (tilt_XXDouble *u, tilt_XXDouble *y, tilt_XXDouble t)
{
	/* Copy the inputs */
	tilt_xx_time = t;
	tilt_XXCopyInputsToVariables (u);

	/* Calculate the model */
	tilt_XXCalculateInput ();
	tilt_XXDiscreteStep ();
	tilt_XXCalculateOutput ();

	/* Copy the outputs */
	tilt_XXCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void tilt_XXTerminateSubmodel (tilt_XXDouble *u, tilt_XXDouble *y, tilt_XXDouble t)
{
	/* Copy the inputs */
	tilt_xx_time = t;
	tilt_XXCopyInputsToVariables (u);

	/* Calculate the final model equations */
	tilt_XXCalculateFinal ();

	/* Set the outputs */
	tilt_XXCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	tilt_XXModelTerminate ();
	tilt_XXDiscreteTerminate ();
}

