/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.h
 *  model: PositionControllerTilt
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:05:31 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef TILT_INTEG_H
#define TILT_INTEG_H

/* 20-sim include files */
#include "tilt_types.h"

/* the chosen integration method */
#define Discrete_METHOD

/* the integration methods */
void tilt_XXDiscreteInitialize (void);
void tilt_XXDiscreteTerminate (void);
void tilt_XXDiscreteStep (void);

extern tilt_XXBoolean tilt_xx_major;

#endif

