/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:05:31 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef TILT_SUBMOD_H
#define TILT_SUBMOD_H

/* Our own include files */
#include "tilt_model.h"

/* Submodel I/O variables */
extern tilt_XXInteger tilt_xx_number_of_inputs;
extern tilt_XXInteger tilt_xx_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern tilt_XXString tilt_xx_input_names[];
extern tilt_XXString tilt_xx_output_names[];


/* The submodel functions */
void tilt_XXInitializeSubmodel (tilt_XXDouble *u, tilt_XXDouble *y, tilt_XXDouble t);
void tilt_XXCalculateSubmodel (tilt_XXDouble *u, tilt_XXDouble *y, tilt_XXDouble t);
void tilt_XXTerminateSubmodel (tilt_XXDouble *u, tilt_XXDouble *y, tilt_XXDouble t);
void tilt_XXCopyInputsToVariables (tilt_XXDouble *u);
void tilt_XXCopyVariablesToOutputs (tilt_XXDouble *y);

#endif

