/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxfuncs.h
 *  model: PositionControllerPan
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:03:39 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

#ifndef PAN_FUNCS_H
#define PAN_FUNCS_H

/* Our own include files */
#include "pan_types.h"

/* Global constants */
extern pan_XXBoolean pan_xx_initialize;
extern pan_XXBoolean pan_xx_major;
extern pan_XXBoolean pan_xx_stop_simulation;

/* Wrapper functions around strings */
pan_XXDouble pan_XXString2Double(const char* argument);
const char* pan_XXDouble2String(pan_XXDouble argument);

/* 20-sim function prototypes */
/* 20-sim stub prototypes */
#endif

