/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:03:39 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "pan_model.h"
#include "pan_integ.h"
#include "pan_funcs.h"
#include "pan_submod.h"
#include "motionprofiles.h"
#include "EulerAngles.h"

/* The submodel I/O variables */
pan_XXInteger pan_xx_number_of_inputs = 2;
pan_XXInteger pan_xx_number_of_outputs = 2;

/* the names of the submodel io variables
   uncomment this part if you need these names
pan_XXString pan_xx_input_names[] = {
	"in",
	"position"
,	NULL
};
pan_XXString pan_xx_output_names[] = {
	"corr",
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void pan_XXCopyInputsToVariables (pan_XXDouble *u)
{
	/* Copy the input vector to the input variables */
	pan_xx_V[7] = u[0];		/* in */
	pan_xx_V[8] = u[1];		/* position */

}

/* This function uses the output variables to fill the output vector */
void pan_XXCopyVariablesToOutputs (pan_XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	pan_xx_V[6];		/* corr */
	y[1] = 	pan_xx_V[9];		/* out */

}

/* The initialization function for submodel */
void pan_XXInitializeSubmodel (pan_XXDouble *u, pan_XXDouble *y, pan_XXDouble t)
{
	/* Initialization phase (allocating memory) */
	pan_xx_initialize = pan_XXTRUE;
	pan_xx_steps = 0;
	pan_XXModelInitialize ();
	pan_XXDiscreteInitialize ();

	/* Copy the inputs */
	pan_xx_time = t;
	pan_XXCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	pan_XXCalculateInitial ();
	pan_XXCalculateStatic ();
	pan_XXCalculateInput ();
	pan_XXCalculateDynamic ();
	pan_XXCalculateOutput ();

	/* Set the outputs */
	pan_XXCopyVariablesToOutputs (y);

	/* End of initialization phase */
	pan_xx_initialize = pan_XXFALSE;
}

/* The function that calculates the submodel */
void pan_XXCalculateSubmodel (pan_XXDouble *u, pan_XXDouble *y, pan_XXDouble t)
{
	/* Copy the inputs */
	pan_xx_time = t;
	pan_XXCopyInputsToVariables (u);

	/* Calculate the model */
	pan_XXCalculateInput ();
	pan_XXDiscreteStep ();
	pan_XXCalculateOutput ();

	/* Copy the outputs */
	pan_XXCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void pan_XXTerminateSubmodel (pan_XXDouble *u, pan_XXDouble *y, pan_XXDouble t)
{
	/* Copy the inputs */
	pan_xx_time = t;
	pan_XXCopyInputsToVariables (u);

	/* Calculate the final model equations */
	pan_XXCalculateFinal ();

	/* Set the outputs */
	pan_XXCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	pan_XXModelTerminate ();
	pan_XXDiscreteTerminate ();
}

