/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:03:39 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef PAN_SUBMOD_H
#define PAN_SUBMOD_H

/* Our own include files */
#include "pan_model.h"

/* Submodel I/O variables */
extern pan_XXInteger pan_xx_number_of_inputs;
extern pan_XXInteger pan_xx_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern pan_XXString pan_xx_input_names[];
extern pan_XXString pan_xx_output_names[];


/* The submodel functions */
void pan_XXInitializeSubmodel (pan_XXDouble *u, pan_XXDouble *y, pan_XXDouble t);
void pan_XXCalculateSubmodel (pan_XXDouble *u, pan_XXDouble *y, pan_XXDouble t);
void pan_XXTerminateSubmodel (pan_XXDouble *u, pan_XXDouble *y, pan_XXDouble t);
void pan_XXCopyInputsToVariables (pan_XXDouble *u);
void pan_XXCopyVariablesToOutputs (pan_XXDouble *y);

#endif

