/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.c
 *  model: PositionControllerPan
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:03:39 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   pan_XXDouble pan_xx_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   pan_XXString pan_xx_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void pan_XXCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>
#include <string.h>

/* 20-sim include files */
#include "pan_model.h"
#include "pan_funcs.h"

/* the global variables */
pan_XXDouble pan_xx_start_time = 0.0;
pan_XXDouble pan_xx_finish_time = 20.0;
pan_XXDouble pan_xx_step_size = 0.01;
pan_XXDouble pan_xx_time = 0.0;
pan_XXInteger pan_xx_steps = 0;
pan_XXBoolean pan_xx_initialize = pan_XXTRUE;
pan_XXBoolean pan_xx_major = pan_XXTRUE;
pan_XXBoolean pan_xx_stop_simulation = pan_XXFALSE;

/* the variable arrays */
pan_XXDouble pan_xx_P[pan_xx_parameters_size];		/* parameters */
pan_XXDouble pan_xx_I[pan_xx_initialvalues_size];		/* initial values */
pan_XXDouble pan_xx_V[pan_xx_variables_size];		/* variables */
pan_XXDouble pan_xx_s[pan_xx_states_size];		/* states */
pan_XXDouble pan_xx_R[pan_xx_states_size];		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
pan_XXString pan_xx_parameter_names[] = {
	"corrGain\\K",
	"PID1\\kp",
	"PID1\\tauD",
	"PID1\\beta",
	"PID1\\tauI",
	"SignalLimiter2\\minimum",
	"SignalLimiter2\\maximum"
,	NULL
};
pan_XXString pan_xx_initial_value_names[] = {
	"PID1\\uD_previous_initial",
	"PID1\\error_previous_initial",
	"PID1\\uI_previous_initial"
,	NULL
};
pan_XXString pan_xx_variable_names[] = {
	"corrGain\\corr",
	"PID1\\output",
	"",
	"PlusMinus1\\plus1",
	"SignalLimiter2\\output",
	"Splitter1\\input",
	"corr",
	"in",
	"position",
	"out"
,	NULL
};
pan_XXString pan_xx_state_names[] = {
	"PID1\\uD_previous",
	"PID1\\error_previous",
	"PID1\\uI_previous"
,	NULL
};
pan_XXString pan_xx_rate_names[] = {
	"",
	"PID1\\error",
	""
,	NULL
};
*/

#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
void pan_XXModelInitialize_parameters(void)
{
	/* set the parameters */
	pan_xx_P[0] = 0.0;		/* corrGain\K */
	pan_xx_P[1] = 2.6;		/* PID1\kp */
	pan_xx_P[2] = 0.05;		/* PID1\tauD */
	pan_xx_P[3] = 0.17;		/* PID1\beta */
	pan_xx_P[4] = 9.0;		/* PID1\tauI */
	pan_xx_P[5] = -0.99;		/* SignalLimiter2\minimum */
	pan_xx_P[6] = 0.99;		/* SignalLimiter2\maximum */

}
#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

void pan_XXModelInitialize_initialvalues(void)
{
	/* set the initial values */
	pan_xx_I[0] = 0.0;		/* PID1\uD_previous_initial */
	pan_xx_I[1] = 0.0;		/* PID1\error_previous_initial */
	pan_xx_I[2] = 0.0;		/* PID1\uI_previous_initial */

}

void pan_XXModelInitialize_states(void)
{
	/* set the states */
	pan_xx_s[0] = pan_xx_I[0];		/* PID1\uD_previous */
	pan_xx_s[1] = pan_xx_I[1];		/* PID1\error_previous */
	pan_xx_s[2] = pan_xx_I[2];		/* PID1\uI_previous */

}

void pan_XXModelInitialize_variables(void)
{
	/* initialize the variable memory to zero */
	memset(pan_xx_V, 0, pan_xx_variables_size * sizeof(pan_XXDouble));
}

/* this method is called before calculation is possible */
void pan_XXModelInitialize (void)
{
	pan_XXModelInitialize_parameters();
	pan_XXModelInitialize_variables();
	pan_XXModelInitialize_initialvalues();
	pan_XXModelInitialize_states();
}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void pan_XXCalculateInitial (void)
{

	/* set the states again, they might have changed in the initial calculation */
	pan_XXModelInitialize_states ();
}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void pan_XXCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void pan_XXCalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void pan_XXCalculateDynamic (void)
{
	/* PID1\factor = 1 / (sampletime + PID1\tauD * PID1\beta); */
	pan_xx_V[2] = 1.0 / (pan_xx_step_size + pan_xx_P[2] * pan_xx_P[3]);

	/* PlusMinus1\plus1 = in; */
	pan_xx_V[3] = pan_xx_V[7];

	/* Splitter1\input = position; */
	pan_xx_V[5] = pan_xx_V[8];

	/* corrGain\corr = corrGain\K * Splitter1\input; */
	pan_xx_V[0] = pan_xx_P[0] * pan_xx_V[5];

	/* PID1\error = PlusMinus1\plus1 - Splitter1\input; */
	pan_xx_R[1] = pan_xx_V[3] - pan_xx_V[5];

	/* PID1\uD = PID1\factor * (((PID1\tauD * PID1\uD_previous) * PID1\beta + (PID1\tauD * PID1\kp) * (PID1\error - PID1\error_previous)) + (sampletime * PID1\kp) * PID1\error); */
	pan_xx_R[0] = pan_xx_V[2] * (((pan_xx_P[2] * pan_xx_s[0]) * pan_xx_P[3] + (pan_xx_P[2] * pan_xx_P[1]) * (pan_xx_R[1] - pan_xx_s[1])) + (pan_xx_step_size * pan_xx_P[1]) * pan_xx_R[1]);

	/* PID1\uI = PID1\uI_previous + (sampletime * PID1\uD) / PID1\tauI; */
	pan_xx_R[2] = pan_xx_s[2] + (pan_xx_step_size * pan_xx_R[0]) / pan_xx_P[4];

	/* PID1\output = PID1\uI + PID1\uD; */
	pan_xx_V[1] = pan_xx_R[2] + pan_xx_R[0];

	/* SignalLimiter2\output = if PID1\output < SignalLimiter2\minimum... ; */
	pan_xx_V[4] = ((pan_xx_V[1] < pan_xx_P[5]) ? 
		/* SignalLimiter2\minimum */
		pan_xx_P[5]
	:
		/* if PID1\output > SignalLimiter2\maximum...  */
		((pan_xx_V[1] > pan_xx_P[6]) ? 
			/* SignalLimiter2\maximum */
			pan_xx_P[6]
		:
			/* PID1\output */
			pan_xx_V[1]
		)
	);


	/* increment the step counter */
	pan_xx_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void pan_XXCalculateOutput (void)
{
	/* corr = corrGain\corr; */
	pan_xx_V[6] = pan_xx_V[0];

	/* out = SignalLimiter2\output; */
	pan_xx_V[9] = pan_xx_V[4];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void pan_XXCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void pan_XXModelTerminate(void)
{
}

