/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:03:39 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef PAN_MODEL_H
#define PAN_MODEL_H

/* Our own include files */
#include "pan_types.h"

/* Simulation variables */
extern pan_XXDouble pan_xx_start_time;
extern pan_XXDouble pan_xx_finish_time;
extern pan_XXDouble pan_xx_step_size;
extern pan_XXDouble pan_xx_time;
extern pan_XXInteger pan_xx_steps;
extern pan_XXBoolean pan_xx_initialize;
extern pan_XXBoolean pan_xx_major;
extern pan_XXBoolean pan_xx_stop_simulation;

/* Model size constants */
#define pan_xx_constants_size 0
#define pan_xx_parameters_size 7
#define pan_xx_initialvalues_size 3
#define pan_xx_variables_size 10
#define pan_xx_states_size 3

/* Variable arrays */
extern pan_XXDouble pan_xx_P[];
extern pan_XXDouble pan_xx_I[];
extern pan_XXDouble pan_xx_V[];
extern pan_XXDouble pan_xx_s[];
extern pan_XXDouble pan_xx_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern pan_XXString pan_xx_parameter_names[];
extern pan_XXString pan_xx_initial_value_names[];
extern pan_XXString pan_xx_variable_names[];
extern pan_XXString pan_xx_state_names[];
extern pan_XXString pan_xx_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void pan_XXModelInitialize (void);
/* Initialize specific model values */
void pan_XXModelInitialize_parameters(void);
void pan_XXModelInitialize_initialvalues(void);
void pan_XXModelInitialize_states(void);
void pan_XXModelInitialize_variables(void);
void pan_XXModelTerminate (void);

/* Computation methods */
void pan_XXCalculateInitial (void);
void pan_XXCalculateStatic (void);
void pan_XXCalculateInput (void);
void pan_XXCalculateDynamic (void);
void pan_XXCalculateOutput (void);
void pan_XXCalculateFinal (void);


#endif

