/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.c
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:03:39 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Discrete
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these as examples.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "pan_integ.h"
#include "pan_model.h"

/* global variables prototypes */
extern pan_XXDouble pan_xx_time;
extern pan_XXDouble pan_xx_step_size;

#define pan_xx_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void pan_XXDiscreteInitialize (void)
{
	/* nothing to be done */
	pan_xx_major = pan_XXTRUE;
}

/* the termination of the Discrete integration method */
void pan_XXDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void pan_XXDiscreteStep (void)
{
	pan_XXInteger index;

	/* for each of the supplied states */
	for (index = 0; index < pan_xx_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		pan_xx_s [index] = pan_xx_R [index];
	}
	/* increment the simulation time */
	pan_xx_time += pan_xx_step_size;

	pan_xx_major = pan_XXTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	pan_XXCalculateDynamic ();
}

