/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.c
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:05:31 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Discrete
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these as examples.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "tilt_integ.h"
#include "tilt_model.h"

/* global variables prototypes */
extern tilt_XXDouble tilt_xx_time;
extern tilt_XXDouble tilt_xx_step_size;

#define tilt_xx_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void tilt_XXDiscreteInitialize (void)
{
	/* nothing to be done */
	tilt_xx_major = tilt_XXTRUE;
}

/* the termination of the Discrete integration method */
void tilt_XXDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void tilt_XXDiscreteStep (void)
{
	tilt_XXInteger index;

	/* for each of the supplied states */
	for (index = 0; index < tilt_xx_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		tilt_xx_s [index] = tilt_xx_R [index];
	}
	/* increment the simulation time */
	tilt_xx_time += tilt_xx_step_size;

	tilt_xx_major = tilt_XXTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	tilt_XXCalculateDynamic ();
}

