/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxfuncs.h
 *  model: PositionControllerTilt
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:05:31 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

#ifndef TILT_FUNCS_H
#define TILT_FUNCS_H

/* Our own include files */
#include "tilt_types.h"

/* Global constants */
extern tilt_XXBoolean tilt_xx_initialize;
extern tilt_XXBoolean tilt_xx_major;
extern tilt_XXBoolean tilt_xx_stop_simulation;

/* Wrapper functions around strings */
tilt_XXDouble tilt_XXString2Double(const char* argument);
const char* tilt_XXDouble2String(tilt_XXDouble argument);

/* 20-sim function prototypes */
/* 20-sim stub prototypes */
#endif

