/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmodel.h
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: 20-BF84
 *  date:  May 22, 2026
 *  time:  5:05:31 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef TILT_MODEL_H
#define TILT_MODEL_H

/* Our own include files */
#include "tilt_types.h"

/* Simulation variables */
extern tilt_XXDouble tilt_xx_start_time;
extern tilt_XXDouble tilt_xx_finish_time;
extern tilt_XXDouble tilt_xx_step_size;
extern tilt_XXDouble tilt_xx_time;
extern tilt_XXInteger tilt_xx_steps;
extern tilt_XXBoolean tilt_xx_initialize;
extern tilt_XXBoolean tilt_xx_major;
extern tilt_XXBoolean tilt_xx_stop_simulation;

/* Model size constants */
#define tilt_xx_constants_size 0
#define tilt_xx_parameters_size 7
#define tilt_xx_initialvalues_size 3
#define tilt_xx_variables_size 12
#define tilt_xx_states_size 3

/* Variable arrays */
extern tilt_XXDouble tilt_xx_P[];
extern tilt_XXDouble tilt_xx_I[];
extern tilt_XXDouble tilt_xx_V[];
extern tilt_XXDouble tilt_xx_s[];
extern tilt_XXDouble tilt_xx_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern tilt_XXString tilt_xx_parameter_names[];
extern tilt_XXString tilt_xx_initial_value_names[];
extern tilt_XXString tilt_xx_variable_names[];
extern tilt_XXString tilt_xx_state_names[];
extern tilt_XXString tilt_xx_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void tilt_XXModelInitialize (void);
/* Initialize specific model values */
void tilt_XXModelInitialize_parameters(void);
void tilt_XXModelInitialize_initialvalues(void);
void tilt_XXModelInitialize_states(void);
void tilt_XXModelInitialize_variables(void);
void tilt_XXModelTerminate (void);

/* Computation methods */
void tilt_XXCalculateInitial (void);
void tilt_XXCalculateStatic (void);
void tilt_XXCalculateInput (void);
void tilt_XXCalculateDynamic (void);
void tilt_XXCalculateOutput (void);
void tilt_XXCalculateFinal (void);


#endif

